site_name: AIAgents4Pharma

nav:
  - Home:
      - Home : home.md
  - Talk2Biomodels : 
      - Talk2Biomodels: talk2biomodels/models/intro.md
      - Models :
        - System Bio Model: talk2biomodels/models/sys_bio_model.md
        - Basico Model : talk2biomodels/models/basico_model.md 
      - Tools :
        - Asking question : talk2biomodels/tools/ask_question.md  
        - Model Description : talk2biomodels/tools/model_description.md 
        - Plotting Figure : talk2biomodels/tools/plot_figure.md  
        - Simulate Model : talk2biomodels/tools/simulate_model.md         

  - Talk2cells :
      - Talk2cells: talk2cells/intro.md

  - Talk2knowledgegraphs :
      - Talk2knowledgegraphs: Talk2KnowledgeGraphs/intro.md 

  - Documentation : 
    - Ops :      
        - Ops : Documentation_intro.md    
        - CodeOps : ops/CodeOps.md
        - DevOps : ops/DevOps.md   
    - Contributing :
        - Contributing : CONTRIBUTING.md    

repo_url: https://github.com/VirtualPatientEngine/AIAgents4Pharma
repo_name: AIAgents4Pharma

theme:
  logo: ./robot.png
  #logo: 🤖
  icon:
    annotation: material/plus-circle 
    repo: fontawesome/brands/github

  extra:
    alternate:
      - name: English
        link: /en/ 
        lang: en
      - name: Deutsch
        link: /de/
        lang: de

  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  name: material
  features :
  - naviation.tabs.sticky
  - navigation.tabs
  - navigation.expand
  - navigation.instant
  - navigation.sections
  - navigation.path
  # - toc.integrate
  - toc.follow
  - navigation.tracking
  - navigation.instant.prefetch
  - navigation.instant.progress
  - navigation.instant.preview
  - navigation.top
  - search.suggest
  - search.heighlight
  - search.share
  - content.code.copy
  - header.autohide


plugins:
  # - search
  - tags
  - mkdocstrings
  # - social:
  #   cards_layout: default/variant
  - search:
      lang: 
        - en
        - de



markdown_extensions:
  - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
