# This is a main workflow to trigger GitHub Actions for specific directories in the repository.
name: Main Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  check-paths:
    runs-on: ubuntu-latest
    outputs:
      talk2biomodels: ${{ steps.set-vars.outputs.talk2biomodels }}
      talk2cells: ${{ steps.set-vars.outputs.talk2cells }}
      talk2knowledgegraphs: ${{ steps.set-vars.outputs.talk2knowledgegraphs }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check changed files
        id: set-vars
        run: |
          echo "Checking for changes in specific aiagents4pharma directories..."
          talk2biomodels=false
          talk2cells=false
          talk2knowledgegraphs=false
          if git diff --name-only HEAD^ HEAD | grep -q '^aiagents4pharma/talk2biomodels/'; then
            talk2biomodels=true
          fi
          if git diff --name-only HEAD^ HEAD | grep -q '^aiagents4pharma/talk2cells/'; then
            talk2cells=true
          fi
          if git diff --name-only HEAD^ HEAD | grep -q '^aiagents4pharma/talk2knowledgegraphs/'; then
            talk2knowledgegraphs=true
          fi
          echo "::set-output name=talk2biomodels::$talk2biomodels"
          echo "::set-output name=talk2cells::$talk2cells"
          echo "::set-output name=talk2knowledgegraphs::$talk2knowledgegraphs"

  trigger-talk2biomodels:
    needs: check-paths
    runs-on: ubuntu-latest
    if: ${{ needs.check-paths.outputs.talk2biomodels == 'true' }}
    steps:
      - name: Trigger Talk2BioModels Workflow
        run: |
          gh workflow run tests_talk2biomodels.yml

  trigger-talk2cells:
    needs: check-paths
    runs-on: ubuntu-latest
    if: ${{ needs.check-paths.outputs.talk2cells == 'true' }}
    steps:
      - name: Trigger Talk2Cells Workflow
        run: |
          gh workflow run tests_talk2cells.yml

  trigger-talk2knowledgegraphs:
    needs: check-paths
    runs-on: ubuntu-latest
    if: ${{ needs.check-paths.outputs.talk2knowledgegraphs == 'true' }}
    steps:
      - name: Trigger Talk2Knowledgegraphs Workflow
        run: |
          gh workflow run tests_talk2knowledgegraphs.yml